version: "3"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/faqtech
      - DB_USERNAME=test-user
      - DB_PASSWORD=test123
      - BASE_URL=http://localhost:5173

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=faqtech
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
